# (Defined host vars (inventory))
# hostname: temporary-hostname
# hardware:
#   disk_name: /dev/sdX
# user:
#   name: raphiz
#   uid: 1000
#   group: raphiz
#   password: 12345
#   password_salt: 12345
# features:
#  - resticTimer
#  - cnijfilter2
#  - virtualbox

# Global packages
base_packages:
  - base
  - reflector
  - pacman-contrib
  - vim
  - git
  - python
  - python-pip
  - python-ruamel-yaml # for ./update-aur-hashes.py
  - openssh
  - unzip
  - zip
  - fd
  - bat
  - ripgrep
  - httpie
  - tree
  - direnv

desktop_apps:
  base:
    - firefox
    - thunderbird
    - libreoffice-fresh-de
    - keepassxc
    - ntfs-3g
    - jq
    - nextcloud-client
  graphic:
    - gimp
    - inkscape
    - imagemagick
  media:
    - vlc
    - audacious
  sytem:
    - wget
    - htop
    - gparted
    - sshfs
    - shellcheck
    - diffuse
    - pacmatic

desktop_apps_aur:
  base:
    - name: google-chrome
      hash: 9fe4701d73b150015febf5bf0c180c5306f73842
    - name: qpdfview
      hash: 550e39c288db6b377e5a23b734d971dc617b6931
    - name: autojump
      hash: df746683f29a323beea8bc233cbfb7efb8f53a6a
    - name: ulauncher
      hash: b2cdeda7b8f5a893ce622f45847c832115e62cf1
# To update this list, use `code --list-extensions`
vscode_extensions:


  # Markdown
  - DavidAnson.vscode-markdownlint
  - mushan.vscode-paste-image

  # Spell checkers
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-german
  - adamvoss.vscode-languagetool
  - adamvoss.vscode-languagetool-de
  - adamvoss.vscode-languagetool-en

  # Other editor goodies
  - EditorConfig.EditorConfig
  - GitHub.github-vscode-theme
  - mikeburgh.xml-format
  - redhat.vscode-yaml
  - VisualStudioExptTeam.vscodeintellicode
  - ms-azuretools.vscode-docker

  # Web development
  - esbenp.prettier-vscode
  - humao.rest-client
  - ms-vscode.vscode-typescript-tslint-plugin
  - octref.vetur

  # Work on remote hosts 🥳
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit

  # Python
  - ms-python.python
  - ms-python.vscode-pylance

  # Linux and shell stuff
  - timonwong.shellcheck
  - foxundermoon.shell-format
  - coolbear.systemd-unit-file


dotfiles: git@github.com:raphiz/dotfiles.git

journal:
  max_size: 500M

base_fonts:
  - terminus-font
  - ttf-dejavu
  - ttf-bitstream-vera
  - ttf-liberation
  - gsfonts
  - tex-gyre-fonts
  - noto-fonts-emoji
  - noto-fonts-cjk
  - ttf-fira-mono
  - ttf-opensans
  - ttf-roboto
  - ttf-roboto-mono
  - ttf-ubuntu-font-family

aur_fonts:
  # Does not work initially...run `yay ttf-symbola`
  - name: ttf-symbola
    hash: 41b127010d6033e7d8de4e0e6d3c1408a07ca5fd
  - name: ttf-ms-fonts
    hash: 4b3621d776c7090b7d42ff53e1aa0170e16477e5
