- hosts: local
  roles:
    - { role: base, tags: ["base"] }

    - { role: xorg, tags: ["xorg"] }
    - { role: lightdm, tags: ["lightdm"] }
    - {
        role: intel-graphics,
        tags: ["intel-graphics"] ,
        when: features is defined and "intel-graphics" in features
      }

    - { role: nettools, tags: ["nettools"] }
    - { role: networkmanager, tags: ["networkmanager"] }
    - { role: ntp, tags: ["ntp"] }

    - { role: audio, tags: ["audio"] }
    - { role: xfce, tags: ["xfce"] }

    - { role: cups, tags: ["cups"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: laptop, tags: ["laptop"] }
    - {
        role: thinkpad,
        tags: ["thinkpad"],
        when: "'ThinkPad' in ansible_product_version",
      }
    - { role: firewall, tags: ["fireall"] }

    - { role: desktop, tags: ["desktop"] }
    - { role: spell, tags: ["spell"] }
    - { role: node, tags: ["node"] }
    - { role: redshift, tags: ["redshift"] }
    - {
        role: sshd,
        tags: ["sshd"],
        when: features is defined and "sshd" in features,
      }
    - { role: yubikey, tags: ["yubikey"] }
    - { role: vscode, tags: ["vscode"] }
    - { role: virtualbox, tags: ["virtualbox"] }
    - { role: docker, tags: ["docker"] }
    - {
        role: bluetooth,
        tags: ["bluetooth"],
        when: features is defined and "bluetooth" in features,
      }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: restic-backup, tags: ["restic-backup"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: snapshots, tags: ["snapshots"] }
