- name: Install code
  aur:
    name: visual-studio-code-bin
    hash: fde93fc7fdcaa83ffaa55d2c88fa69516e6a7158
    user: "{{ user.name }}"

- name: Installing extensions
  command: /usr/bin/code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ user.name }}"
