- name: Install code
  aur:
    name: visual-studio-code-bin
    hash: 832576b3e899336ef7c58fcfa62600080a8cf9c6
    user: "{{ user.name }}"

- name: Installing extensions
  command: /usr/bin/code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ user.name }}"
